[Finishes #187354184] Set up the frontend repository
atlp-rwanda/e-commerce-mavericks-fn pull request #1
Opened 2024-05-22 17:55 UTC by Favor-star

## What has been done so far?
In this PR, I have managed to set up the the react front end repository using `vite` command: `npm create vite@latest` as well as setting up the `tailwind css`.
*All of the files were added for the first time, and tailwind css is working as intended.*

2024-05-22 19:04 UTC, hozayves approved these changes

2024-05-23 10:35 UTC, niyontwali requested changes
Please work on the feedback provided on specific files and as the below'

1. Create a PR template.
2. Implement Husky.
3. Implement ESLint and Prettier.
4. Delete the styles, config, and context folders.

Otherwise the rest look better

2024-05-23 10:35 UTC, niyontwali commented on index.html
> +</html>
Please refine this file to include the following 

1. Usefully meta data for SEOs
2. Include a favicon
3. Include a proper title for our e-commerce

2024-05-23 10:35 UTC, niyontwali commented on src/App.css
> +}
Please remove this whole file we shall use the index.css and also delete the global.css.

2024-05-23 10:35 UTC, niyontwali commented on src/assets/styles/styles.css
> +}
Remove this file and its folder

2024-05-23 19:22 UTC, Munezero2000 approved these changes
LGTM

2024-05-23 19:47 UTC, JeanIrad approved these changes

2024-05-24 06:50 UTC, niyontwali approved these changes

2024-05-24 08:07 UTC, niyontwali approved these changes

2024-05-24 08:07 UTC, merged