[Finshes #187354196] Sign up page
atlp-rwanda/e-commerce-mavericks-fn pull request #10
Opened 2024-06-04 15:53 UTC by Favor-star

## Purpose
The purpose of this PR is to create a sign up page to the mavericks e-commerce

## Changes Made

Created: 
- Sign Up page
- InfoTip Component
- Navbar component
- RegisterComponent

Added:
- Register route to the `app.tsx`

## Testing Instructions

No tests yet

## Related Issues

No issues yet

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [x] Code follows the project's coding standards
- [ ] Changes are covered by tests
- [ ] Documentation is updated (if applicable)
- [ ] All tests pass

2024-06-12 07:33 UTC, Munezero2000 commented on src/components/register/RegisterSection.tsx
> +      const response: Response = await fetch(dbLinks['hosted'], {
can you use Redux ToolKit Query instead of this. I think it is what we agreed on using

2024-06-13 12:15 UTC, patrickhag commented on package.json
> +    "lucide-react": "^0.387.0",
I thought we've agreed to use `react-icons` instead of this package. Isn't it?

2024-06-13 12:19 UTC, patrickhag requested changes, later dismissed
consider removing that package

2024-06-13 12:19 UTC, patrickhag commented on package.json
> +    "lucide-react": "^0.387.0",
I thought we've agreed to use react-icons instead of this package. Isn't it?

2024-06-13 16:17 UTC, niyontwali approved these changes

2024-06-13 16:17 UTC, hozayves approved these changes

2024-06-13 16:17 UTC, hozayves commented on src/components/InfoTip.tsx
Why do we need this infotip component??

2024-06-13 16:17 UTC, hozayves commented on src/components/RegisterSection.tsx
> +const schema = z
Make a new folder specifically for validation and place the zod schema inside it for your signup page.

2024-06-13 16:18 UTC, P-Rwirangira approved these changes

2024-06-13 16:19 UTC, niyontwali approved these changes

2024-06-13 16:19 UTC, hozayves approved these changes

2024-06-13 16:19 UTC, merged