[finishes #187748153] hero-and-categories-sections-ui-implementation
atlp-rwanda/e-commerce-mavericks-fn pull request #12
Opened 2024-06-10 09:59 UTC by amin-leon

## Purpose

Describe the purpose of the PR

## Changes Made

Describe the changes made

## Testing Instructions

List all testing instruction, if availbale

## Related Issues

Lists all related issues

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [ ] Code follows the project's coding standards
- [ ] Changes are covered by tests
- [ ] Documentation is updated (if applicable)
- [ ] All tests pass

2024-06-10 19:46 UTC, hozayves requested changes
Hi NP,
I appreciate the amazing effort you've put in, but I have some feedback:

- Could you align your work more closely with the design in Figma?
- I'm curious how your design would accommodate 100 categories.

2024-06-10 19:53 UTC, amin-leon commented
> Hi NP, I appreciate the amazing effort you've put in, but I have some feedback:
> 
> * Could you align your work more closely with the design in Figma?
> * I'm curious how your design would accommodate 100 categories.

How about on figma for 100 ? can u show me how it can be handled?

2024-06-10 19:55 UTC, amin-leon commented
> Hi NP, I appreciate the amazing effort you've put in, but I have some feedback:
> 
> * Could you align your work more closely with the design in Figma?
> * I'm curious how your design would accommodate 100 categories.

can you show the difference? those categories cards, right ?? i have explained it why i changed them

2024-06-10 20:06 UTC, hozayves commented
> > Hi NP, I appreciate the amazing effort you've put in, but I have some feedback:
> > 
> > * Could you align your work more closely with the design in Figma?
> > * I'm curious how your design would accommodate 100 categories.
> 
> can you show the difference? those categories cards, right ?? i have explained it why i changed them

I wasn't on the call, so I'm not sure why you decided to change the design.

2024-06-10 20:07 UTC, amin-leon commented
> > > Hi NP, I appreciate the amazing effort you've put in, but I have some feedback:
> > > 
> > > * Could you align your work more closely with the design in Figma?
> > > * I'm curious how your design would accommodate 100 categories.
> > 
> > 
> > can you show the difference? those categories cards, right ?? i have explained it why i changed them
> 
> I wasn't on the call, so I'm not sure why you decided to change the design.

you were not! okay

2024-06-10 20:09 UTC, hozayves commented
> > > Hi NP, I appreciate the amazing effort you've put in, but I have some feedback:
> > > 
> > > * Could you align your work more closely with the design in Figma?
> > > * I'm curious how your design would accommodate 100 categories.
> > 
> > 
> > can you show the difference? those categories cards, right ?? i have explained it why i changed them
> 
> I wasn't on the call, so I'm not sure why you decided to change the design.

You need to write it in a way that anyone, at any time, can read and understand it.

2024-06-10 20:11 UTC, hozayves commented
> > > > Hi NP, I appreciate the amazing effort you've put in, but I have some feedback:
> > > > 
> > > > * Could you align your work more closely with the design in Figma?
> > > > * I'm curious how your design would accommodate 100 categories.
> > > 
> > > 
> > > can you show the difference? those categories cards, right ?? i have explained it why i changed them
> > 
> > 
> > I wasn't on the call, so I'm not sure why you decided to change the design.
> 
> you were not! okay

NP, during the demo time, I wasn't in the meeting. I joined a bit late.

2024-06-10 20:12 UTC, amin-leon commented
> > > > Hi NP, I appreciate the amazing effort you've put in, but I have some feedback:
> > > > 
> > > > * Could you align your work more closely with the design in Figma?
> > > > * I'm curious how your design would accommodate 100 categories.
> > > 
> > > 
> > > can you show the difference? those categories cards, right ?? i have explained it why i changed them
> > 
> > 
> > I wasn't on the call, so I'm not sure why you decided to change the design.
> 
> You need to write it in a way that anyone, at any time, can read and understand it.

what to write and understand? mn be specific boy!

2024-06-14 15:44 UTC, hozayves approved these changes

2024-06-14 15:44 UTC, Munezero2000 approved these changes

2024-06-14 15:44 UTC, Mag-codes commented on package.json
>      "lucide-react": "^0.387.0",
can we use one Library for Icons here we have lucide-react and react-icons. I think react-icons might be good

2024-06-14 15:50 UTC, niyontwali approved these changes

2024-06-14 15:53 UTC, patrickhag requested changes
consider removing those console logs man

2024-06-14 15:53 UTC, patrickhag commented on src/containers/Arrivals/NewArrivals.tsx
> +    console.log("Loading...");
You should those log in codebase?

2024-06-14 15:53 UTC, patrickhag commented on src/containers/Arrivals/NewArrivals.tsx
> +    console.log("No products data received");
even here

2024-06-14 15:55 UTC, Favor-star requested changes
ESPECIALLY REMOVE THAT POSITION FIXED TOU SET ON NAVBAR, BRING IT BACK TO STICKY.
You was not around yesterday that is why; bbut may ask me reasons later.

2024-06-14 15:55 UTC, Favor-star commented on src/components/navbar/Navbar.tsx
> +        <div className='flex flex-col bg-blackColor md:bg-whiteColor md:text-blackColor text-whiteColor font-roboto w-full 2xl:items-center fixed z-50'>
This was a bug we removed yesterday on call. Yet you're returning it. why?

2024-06-14 15:55 UTC, Favor-star commented on src/containers/FeaturedProducts/FeaturedProducts.tsx
> +    console.log("No products data received");
Console.log? Is this okay? How a standard user gonna see this?

2024-06-14 15:56 UTC, patrickhag approved these changes

2024-06-14 15:57 UTC, merged