User should be able to search across the web
atlp-rwanda/e-commerce-mavericks-fn pull request #26
Opened 2024-06-24 09:00 UTC by Favor-star

## Purpose

This PR is intended to make the user be able to search across the websites  through search input in navbar

## Changes Made

Created search pages including search header and search results components 

## Testing Instructions

No tests made yet

## Related Issues

THe issues is with redux. Data seems not stored in redux. which requires me to re-request data from backend.

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [x] Code follows the project's coding standards
- [x] Changes are covered by tests
- [x] Documentation is updated (if applicable)
- [x] All tests pass
![Screenshot 2024-06-24 105900](https://github.com/atlp-rwanda/e-commerce-mavericks-fn/assets/136271852/ed82f1a2-4eec-4372-9df8-449dd05ff4b4)

2024-06-24 11:27 UTC, patrickhag requested changes
consider these comments!

2024-06-24 11:27 UTC, patrickhag commented on src/components/search/SearchResults.tsx
> +  console.log(productsList);
can you remove console.logs?

2024-06-24 11:27 UTC, patrickhag commented on src/components/search/SearchResults.tsx
> +  // }, [productFetched, products]);
why's this code commented?

2024-06-24 20:31 UTC, gracemugwanezak approved these changes

2024-06-24 21:11 UTC, patrickhag approved these changes
LGTM

2024-06-25 09:05 UTC, Munezero2000 requested changes

2024-06-25 09:05 UTC, Mag-codes commented on src/components/search/SearchResults.tsx
> +    product.name.toLowerCase().includes(searchQuery.toLowerCase())
![image](https://github.com/atlp-rwanda/e-commerce-mavericks-fn/assets/101561925/fae166b6-ead8-4b18-aa20-003b414cbb97)

include more than  search by product name

2024-06-25 09:05 UTC, Mag-codes commented on src/components/search/SearchResults.tsx
> +            No matching products were found for <span className='font-bold'>{searchQuery}</span>
![image](https://github.com/atlp-rwanda/e-commerce-mavericks-fn/assets/101561925/857058e1-90ca-489a-9707-80dcaecd2d18)

Show available products as a user types in a overlay

2024-06-27 16:48 UTC, hozayves approved these changes

2024-06-27 17:35 UTC, P-Rwirangira approved these changes

2024-06-27 17:50 UTC, closed without merging