Bg fix use redux store
atlp-rwanda/e-commerce-mavericks-fn pull request #28
Opened 2024-06-24 20:25 UTC by Favor-star

## Purpose

The purpose of this PR was to fix the error where products were being fetched multiple times. I made sure that the products are fetched once and then store within redux store, for oother uses

## Changes Made

removed fetch requests from different multiple filea and intergrated them in the `app.jsx` to make sure that the request is done once and transimitted accross the all other files.

## Testing Instructions
No tests so far.

## Related Issues

No issues

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [x] Code follows the project's coding standards
- [x] Changes are covered by tests
- [x] Documentation is updated (if applicable)
- [x] All tests pass

2024-06-26 08:02 UTC, niyontwali requested changes

2024-06-26 08:02 UTC, niyontwali commented on src/containers/Arrivals/NewArrivals.tsx
> +  const productsList: Product[] = useSelector((state: any) => state.products.productsDataList);
Could you combine this code and use destructuring like const { } = useSelector((state: any) => state.products)?

2024-06-26 08:02 UTC, niyontwali commented on src/containers/FeaturedProducts/FeaturedProducts.tsx
> +  const productsList: Product[] = useSelector((state: any) => state.products.productsDataList);
The same here use destructuring

2024-06-27 04:13 UTC, amin-leon reviewed
Checkout my comments

2024-06-27 04:13 UTC, amin-leon commented on src/components/search/SearchHeader.tsx
I think we can use other figma page i designed rather than this.

2024-06-27 04:13 UTC, amin-leon commented on src/components/search/SearchResults.tsx
I think we can use other figma page i designed rather than this.

2024-06-27 13:12 UTC, Favor-star commented on src/components/search/SearchResults.tsx
is there a page dedicated for search results in Figma?

2024-06-27 15:59 UTC, hozayves approved these changes

2024-06-27 16:35 UTC, amin-leon approved these changes

2024-06-27 16:41 UTC, P-Rwirangira approved these changes

2024-06-27 17:34 UTC, niyontwali approved these changes

2024-06-27 17:34 UTC, merged