[finishes #187354194 setup github actions to run test]
atlp-rwanda/e-commerce-mavericks-fn pull request #8
Opened 2024-05-28 20:11 UTC by hatfelicien

## Purpose

The purpose of this pull request is to add the Coveralls badge to the README file of the repository.

## Changes Made

- Added the Coveralls badge HTML embed code to the README.md file.
- Ensured that the badge integrates seamlessly with existing badges and content.

## Testing Instructions

1. Ensure that the badge appears correctly in the README file.
2. Click on the badge to verify that it redirects to the correct Coveralls page for the repository.
3. Check the rendering of the README file on different Markdown viewers or previewers to ensure consistent display.

## Related Issues

no issue

## Checklist

Please review the following checklist and make sure all tasks are complete before submitting:

- [x] Code follows the project's coding standards
- [x] Changes are covered by tests
- [x] Documentation is updated (if applicable)
- [x] All tests pass

2024-05-30 10:09 UTC, Favor-star approved these changes
Looks good to me

2024-05-31 11:01 UTC, P-Rwirangira reviewed
You did a great work but there is a problem with the test:
  -Couldn't find specified file: ./coverage/lcov.info (The file that contains test results )
![Screenshot 2024-05-31 125937](https://github.com/atlp-rwanda/e-commerce-mavericks-fn/assets/142627846/75c0cc85-a6bc-4184-80cb-682d8e68331b)

2024-06-04 16:13 UTC, niyontwali requested changes
Could you please check on the coverage folder, if all those files can be regenerated they should be in the gitignore. There are so many tasks am seeing that should not be pushed

2024-06-04 16:30 UTC, hozayves approved these changes

2024-06-05 05:16 UTC, niyontwali approved these changes

2024-06-05 05:16 UTC, merged